name: Custom checks

on: [pull_request]

jobs:
  block-fixup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout on branch
        uses: actions/checkout@v2
      - name: Block Merge action in presence of fixup
        uses: 13rac1/block-fixup-merge-action@v2.0.0
