name: Job Tester

on:
  pull_request:
    types: [ labeled ]
    
jobs:
  job-test:
    name: Job Test
    runs-on: ubuntu-latest

    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Set local git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - run: git rebase -i --autosquash ${{ github.pull_request.base.sha }}
        env:
          EDITOR: true
      - name: Add Tag on last commit
        run: git tag feature_${{ github.head_ref }}
      - name: Push on current branch
        run: git push --force-with-lease origin ${{ github.head_ref }}
