name: Job Tester

on:
  pull_request:
    types: [ labeled ]
    
jobs:
  job-test:
    name: Job Test
    runs-on: ubuntu-latest

    env:
      github_head_ref: ${{ github.head_ref }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Rebase autosquash
        run: git rebase -i --autosquash ${{ github.base_ref }}
      - name: Push on current branch
        run: git push origin ${{ github.head_ref }}
