name: Job Tester

on:
  pull_request:
    types: [ labeled ]
    
jobs:
  job-test:
    name: Job Test
    runs-on: ubuntu-latest

    env:
      github_head_ref: ${{ github }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v1
      - name: Print event
      	run: |
	  echo ${{ env.github_head_ref }}
	  echo ${{ github.head_ref }}
	  echo ${{ github.base_ref }}
